export const projects = [
  {
    title: "projectKeyboardTitle",
    description: "projectKeyboardDescription",
    image: "./images/-4.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/game-for-you",
    website: "https://game-for-you-tawny.vercel.app/",
  },
  {
    title: "projectMoviesTitle",
    description: "projectMoviesDescription",
    image: "./images/-3.webp",
    technologies: ["React", "TypeScript", "JS"],
    github: "https://github.com/ljresetl/03-react-movies",
    website: "https://03-react-movies-one-liard.vercel.app/",
  },
  {
    title: "projectMusicAppTitle",
    description: "projectMusicAppDescription",
    image: "./images/-2.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/pattaroni/project-Dev4L1fe",
    website: "https://pattaroni.github.io/project-Dev4L1fe/",
  },
  {
    title: "projectMusicPortfolioTitle",
    description: "projectMusicPortfolioDescription",
    image: "./images/-1.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/New-Single-Dj",
    website: "https://ljresetl.github.io/New-Single-Dj/",
  },
  {
    title: "projectFinancialTitle",
    description: "projectFinancialDescription",
    image: "./images/foto1.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/financial_consulting",
    website: "https://ljresetl.github.io/financial_consulting/",
  },
  {
    title: "projectCinemaTitle",
    description: "projectCinemaDescription",
    image: "./images/kino411.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/kino2",
    website: "https://ljresetl.github.io/kino2/",
  },
  {
    title: "projectBarbershopTitle",
    description: "projectBarbershopDescription",
    image: "./images/priklad3-411x350.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/barbershop",
    website: "https://ljresetl.github.io/barbershop/",
  },
  {
    title: "projectWebStudioTitle",
    description: "projectWebStudioDescription",
    image: "./images/maket411.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/PRODUCT-business",
    website: "https://ljresetl.github.io/PRODUCT-business/",
  },
  {
    title: "projectYachtsTitle",
    description: "projectYachtsDescription",
    image: "./images/projekt411x266.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/team-work-yachtjet",
    website: "https://ljresetl.github.io/team-work-yachtjet/",
  },
  {
    title: "projectWeatherTitle",
    description: "projectWeatherDescription",
    image: "./images/fotoýproject.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/weather-html-css-js",
    website: "https://ljresetl.github.io/weather-html-css-js/",
  },
  {
    title: "projectSWESTitle",
    description: "projectSWESDescription",
    image: "./images/priklad8.webp",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/ljresetl/SWES-Reservation-Module",
    website: "https://ljresetl.github.io/SWES-Reservation-Module/",
  },
];
